# OFDM系统配置参数
n_fft: 4096
cp_len: 320
mod_order: 6  # QPSK
num_symbols: 14
snr_db: 35
n_subcarrier: 3276
pilot_pattern: comb
pilot_spacing: 2
pilot_symbols: [1,12]
freq_offset: 0.02
timing_offset: 100
est_time: fft_ml  #fft_ml/diff_phase
channel_type: awgn  #awgn/multipath
display_est_result: false
