# OFDM系统配置参数
n_fft: 4096
cp_len: 320
mod_order: 6  # QPSK/16QAM/64QAM
num_symbols: 14
snr_db: 15
n_subcarrier: 3276
num_rx_ant: 2
code_rate: 0.5
pilot_pattern: comb
pilot_spacing: 2
pilot_symbols: [2,11]
freq_offset: 0.02
timing_offset: 100
est_time: fft_ml  #fft_ml/diff_phase/ml_then_phase
channel_type: sionna_tdl  #awgn/multipath/rayleigh/sionna_fading/sionna_tdl
display_est_result: false
interp_method: nearest  # linear or nearest
