# OFDM系统配置参数
n_fft: 4096
cp_len: 320
mod_order: 6  # QPSK
num_symbols: 14
snr_db: 15
n_subcarrier: 3276
pilot_pattern: comb
pilot_spacing: 2
pilot_symbols: [0,13]
freq_offset: 0.02
timing_offset: 100
est_time: diff_phase  #fft_ml/diff_phase
channel_type: rayleigh  #awgn/multipath/rayleigh
display_est_result: true
