classdef Shape_To_SliceLayer1323 < nnet.layer.Layer & nnet.layer.Formattable
    % A custom layer auto-generated while importing an ONNX network.

    %#codegen
    %#ok<*PROPLC>
    %#ok<*NBRAK>
    %#ok<*INUSL>
    %#ok<*VARARG>

    properties (Learnable)
    end

    properties
        ONNXParams         % An ONNXParameters object containing parameters used by this layer.
    end

    methods
        function this = Shape_To_SliceLayer1323(name, onnxParams)
            this.Name = name;
            this.NumInputs = 2;
            this.OutputNames = {'Slice__135_0'};
            this.ONNXParams = onnxParams;
        end

        function [Slice__135_0] = predict(this, n_nrecevier_mod_26, n_nrecevier_mod_4)
            if isdlarray(n_nrecevier_mod_26)
                n_nrecevier_mod_26 = stripdims(n_nrecevier_mod_26);
            end
            if isdlarray(n_nrecevier_mod_4)
                n_nrecevier_mod_4 = stripdims(n_nrecevier_mod_4);
            end
            n_nrecevier_mod_26NumDims = 4;
            n_nrecevier_mod_4NumDims = 4;
            onnxParams = this.ONNXParams;
            [Slice__135_0, Slice__135_0NumDims] = Shape_To_SliceFcn(n_nrecevier_mod_26, n_nrecevier_mod_4, n_nrecevier_mod_26NumDims, n_nrecevier_mod_4NumDims, onnxParams, 'Training', false, ...
                'InputDataPermutation', {[4 1 2 3], [4 3 1 2], ['as-is'], ['as-is']}, ...
                'OutputDataPermutation', {[3 4 2 1], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {Slice__135_0}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'Shape_To_SliceLayer1323');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Shape_To_SliceLayer1323'));
            end
            Slice__135_0 = dlarray(single(Slice__135_0), 'SSCB');
            if ~coder.target('MATLAB')
                Slice__135_0 = extractdata(Slice__135_0);
            end
        end

        function [Slice__135_0] = forward(this, n_nrecevier_mod_26, n_nrecevier_mod_4)
            if isdlarray(n_nrecevier_mod_26)
                n_nrecevier_mod_26 = stripdims(n_nrecevier_mod_26);
            end
            if isdlarray(n_nrecevier_mod_4)
                n_nrecevier_mod_4 = stripdims(n_nrecevier_mod_4);
            end
            n_nrecevier_mod_26NumDims = 4;
            n_nrecevier_mod_4NumDims = 4;
            onnxParams = this.ONNXParams;
            [Slice__135_0, Slice__135_0NumDims] = Shape_To_SliceFcn(n_nrecevier_mod_26, n_nrecevier_mod_4, n_nrecevier_mod_26NumDims, n_nrecevier_mod_4NumDims, onnxParams, 'Training', true, ...
                'InputDataPermutation', {[4 1 2 3], [4 3 1 2], ['as-is'], ['as-is']}, ...
                'OutputDataPermutation', {[3 4 2 1], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {Slice__135_0}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'Shape_To_SliceLayer1323');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Shape_To_SliceLayer1323'));
            end
            Slice__135_0 = dlarray(single(Slice__135_0), 'SSCB');
            if ~coder.target('MATLAB')
                Slice__135_0 = extractdata(Slice__135_0);
            end
        end
    end
end

function [Slice__135_0, Slice__135_0NumDims, state] = Shape_To_SliceFcn(n_nrecevier_mod_26, n_nrecevier_mod_4, n_nrecevier_mod_26NumDims, n_nrecevier_mod_4NumDims, params, varargin)
%SHAPE_TO_SLICEFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 18
%
% Variable names in this function are taken from the original ONNX file.
%
% [SLICE__135_0] = Shape_To_SliceFcn(N_NRECEVIER_MOD_26, N_NRECEVIER_MOD_4, PARAMS)
%			- Evaluates the imported ONNX network SHAPE_TO_SLICEFCN with input(s)
%			N_NRECEVIER_MOD_26, N_NRECEVIER_MOD_4 and the imported network parameters in PARAMS. Returns
%			network output(s) in SLICE__135_0.
%
% [SLICE__135_0, STATE] = Shape_To_SliceFcn(N_NRECEVIER_MOD_26, N_NRECEVIER_MOD_4, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = Shape_To_SliceFcn(N_NRECEVIER_MOD_26, N_NRECEVIER_MOD_4, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% N_NRECEVIER_MOD_26, N_NRECEVIER_MOD_4
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  N_NRECEVIER_MOD_26:		[Unknown, Unknown, Unknown, Unknown]				Type: FLOAT
%				  N_NRECEVIER_MOD_4:		[Unknown, Unknown, Unknown, Unknown]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% SLICE__135_0
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  SLICE__135_0:		[Unknown, Unknown, Unknown, Unknown]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[n_nrecevier_mod_26, n_nrecevier_mod_4, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(n_nrecevier_mod_26, n_nrecevier_mod_4, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'n_nrecevier_mod_26', 'n_nrecevier_mod_4'}, {n_nrecevier_mod_26, n_nrecevier_mod_4}, [n_nrecevier_mod_26NumDims n_nrecevier_mod_4NumDims]);
% Call the top-level graph function:
[Slice__135_0, Slice__135_0NumDims, state] = Shape_To_SliceGraph1319(n_nrecevier_mod_26, n_nrecevier_mod_4, NumDims.n_nrecevier_mod_26, NumDims.n_nrecevier_mod_4, Vars, NumDims, Training, params.State);
% Postprocess the output data
[Slice__135_0] = postprocessOutput(Slice__135_0, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [Slice__135_0, Slice__135_0NumDims1322, state] = Shape_To_SliceGraph1319(n_nrecevier_mod_26, n_nrecevier_mod_4, n_nrecevier_mod_26NumDims1320, n_nrecevier_mod_4NumDims1321, Vars, NumDims, Training, state)
% Function implementing the graph 'Shape_To_SliceGraph1319'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.n_nrecevier_mod_26 = n_nrecevier_mod_26;
NumDims.n_nrecevier_mod_26 = n_nrecevier_mod_26NumDims1320;
Vars.n_nrecevier_mod_4 = n_nrecevier_mod_4;
NumDims.n_nrecevier_mod_4 = n_nrecevier_mod_4NumDims1321;

% Execute the operators:
% Shape:
[Vars.n_nrecevier_mod_6, NumDims.n_nrecevier_mod_6] = onnxShape(Vars.n_nrecevier_mod_26, NumDims.n_nrecevier_mod_26, 0, NumDims.n_nrecevier_mod_26+1);

% Cast:
if islogical(Vars.n_nrecevier_mod_6)
    Vars.n_nrecevier_mod_6 = single(Vars.n_nrecevier_mod_6);
end
Vars.n_nrecevier_mod_7 = cast(int32(extractdata(Vars.n_nrecevier_mod_6)), 'like', Vars.n_nrecevier_mod_6);
NumDims.n_nrecevier_mod_7 = NumDims.n_nrecevier_mod_6;

% Slice:
[Indices, NumDims.n_nrecevier_mod_17] = prepareSliceArgs(Vars.n_nrecevier_mod_7, Vars.const_starts__1983, Vars.const__738, Vars.const_axes__4255, '', NumDims.n_nrecevier_mod_7);
Vars.n_nrecevier_mod_17 = subsref(Vars.n_nrecevier_mod_7, Indices);

% Squeeze:
[Vars.n_nrecevier_mod_18, NumDims.n_nrecevier_mod_18] = onnxSqueeze(Vars.n_nrecevier_mod_17, Vars.const_axes__4255, NumDims.n_nrecevier_mod_17);

% Add:
Vars.n_nrecevier_mod_9 = Vars.n_nrecevier_mod_18 + Vars.n_nrecevier_mod_40;
NumDims.n_nrecevier_mod_9 = max(NumDims.n_nrecevier_mod_18, NumDims.n_nrecevier_mod_40);

% Unsqueeze:
[shape, NumDims.n_nrecevier_mod_13] = prepareUnsqueezeArgs(Vars.n_nrecevier_mod_9, Vars.const_axes__4255, NumDims.n_nrecevier_mod_9);
Vars.n_nrecevier_mod_13 = reshape(Vars.n_nrecevier_mod_9, shape);

% Slice:
[Indices, NumDims.n_nrecevier_mod_15] = prepareSliceArgs(Vars.n_nrecevier_mod_7, Vars.const_starts__1988, Vars.const_starts__1983, Vars.const_axes__4255, '', NumDims.n_nrecevier_mod_7);
Vars.n_nrecevier_mod_15 = subsref(Vars.n_nrecevier_mod_7, Indices);

% Squeeze:
[Vars.n_nrecevier_mod_16, NumDims.n_nrecevier_mod_16] = onnxSqueeze(Vars.n_nrecevier_mod_15, Vars.const_axes__4255, NumDims.n_nrecevier_mod_15);

% Add:
Vars.n_nrecevier_mod_8 = Vars.n_nrecevier_mod_16 + Vars.n_nrecevier_mod_40;
NumDims.n_nrecevier_mod_8 = max(NumDims.n_nrecevier_mod_16, NumDims.n_nrecevier_mod_40);

% Unsqueeze:
[shape, NumDims.n_nrecevier_mod_12] = prepareUnsqueezeArgs(Vars.n_nrecevier_mod_8, Vars.const_axes__4255, NumDims.n_nrecevier_mod_8);
Vars.n_nrecevier_mod_12 = reshape(Vars.n_nrecevier_mod_8, shape);

% Slice:
[Indices, NumDims.n_nrecevier_mod_14] = prepareSliceArgs(Vars.n_nrecevier_mod_7, Vars.const_axes__4255, Vars.const_starts__1988, Vars.const_axes__4255, '', NumDims.n_nrecevier_mod_7);
Vars.n_nrecevier_mod_14 = subsref(Vars.n_nrecevier_mod_7, Indices);

% Concat:
[Vars.n_nrecevier_mod_11, NumDims.n_nrecevier_mod_11] = onnxConcat(0, {Vars.n_nrecevier_mod_14, Vars.n_nrecevier_mod_12, Vars.n_nrecevier_mod_13, Vars.const_fold_opt__6008}, [NumDims.n_nrecevier_mod_14, NumDims.n_nrecevier_mod_12, NumDims.n_nrecevier_mod_13, NumDims.const_fold_opt__6008]);

% Shape:
[Vars.Shape__5365_0, NumDims.Shape__5365_0] = onnxShape(Vars.n_nrecevier_mod_4, NumDims.n_nrecevier_mod_4, 0, NumDims.n_nrecevier_mod_4+1);

% Gather:
[Vars.Shape__107_0, NumDims.Shape__107_0] = onnxGather(Vars.Shape__5365_0, Vars.Const__5379, 0, NumDims.Shape__5365_0, NumDims.Const__5379);

% Slice:
[Indices, NumDims.Slice__116_0] = prepareSliceArgs(Vars.Shape__107_0, Vars.const_starts__1983, Vars.const__738, Vars.const_axes__4255, '', NumDims.Shape__107_0);
Vars.Slice__116_0 = subsref(Vars.Shape__107_0, Indices);

% Slice:
[Indices, NumDims.Slice__112_0] = prepareSliceArgs(Vars.Shape__107_0, Vars.const_starts__1988, Vars.const_starts__1983, Vars.const_axes__4255, '', NumDims.Shape__107_0);
Vars.Slice__112_0 = subsref(Vars.Shape__107_0, Indices);

% Cast:
if islogical(Vars.n_nrecevier_mod_11)
    Vars.n_nrecevier_mod_11 = single(Vars.n_nrecevier_mod_11);
end
Vars.Cast__106_0 = cast(int64(extractdata(Vars.n_nrecevier_mod_11)), 'like', Vars.n_nrecevier_mod_11);
NumDims.Cast__106_0 = NumDims.n_nrecevier_mod_11;

% Slice:
[Indices, NumDims.Slice__124_0] = prepareSliceArgs(Vars.Cast__106_0, Vars.const_starts__1983, Vars.const__738, Vars.const_axes__4255, '', NumDims.Cast__106_0);
Vars.Slice__124_0 = subsref(Vars.Cast__106_0, Indices);

% Sub:
Vars.Sub__126_0 = Vars.Slice__116_0 - Vars.Slice__124_0;
NumDims.Sub__126_0 = max(NumDims.Slice__116_0, NumDims.Slice__124_0);

% Div:
Vars.Div__129_0 = fix(Vars.Sub__126_0 ./ Vars.const_starts__1983);
NumDims.Div__129_0 = max(NumDims.Sub__126_0, NumDims.const_starts__1983);

% Slice:
[Indices, NumDims.Slice__120_0] = prepareSliceArgs(Vars.Cast__106_0, Vars.const_starts__1988, Vars.const_starts__1983, Vars.const_axes__4255, '', NumDims.Cast__106_0);
Vars.Slice__120_0 = subsref(Vars.Cast__106_0, Indices);

% Sub:
Vars.Sub__125_0 = Vars.Slice__112_0 - Vars.Slice__120_0;
NumDims.Sub__125_0 = max(NumDims.Slice__112_0, NumDims.Slice__120_0);

% Div:
Vars.Div__128_0 = fix(Vars.Sub__125_0 ./ Vars.const_starts__1983);
NumDims.Div__128_0 = max(NumDims.Sub__125_0, NumDims.const_starts__1983);

% Concat:
[Vars.Concat__132_0, NumDims.Concat__132_0] = onnxConcat(0, {Vars.Div__128_0, Vars.Div__129_0}, [NumDims.Div__128_0, NumDims.Div__129_0]);

% Add:
Vars.Add__131_0 = Vars.Div__129_0 + Vars.Slice__124_0;
NumDims.Add__131_0 = max(NumDims.Div__129_0, NumDims.Slice__124_0);

% Add:
Vars.Add__130_0 = Vars.Div__128_0 + Vars.Slice__120_0;
NumDims.Add__130_0 = max(NumDims.Div__128_0, NumDims.Slice__120_0);

% Concat:
[Vars.Concat__133_0, NumDims.Concat__133_0] = onnxConcat(0, {Vars.Add__130_0, Vars.Add__131_0}, [NumDims.Add__130_0, NumDims.Add__131_0]);

% Slice:
[Indices, NumDims.Slice__135_0] = prepareSliceArgs(Vars.n_nrecevier_mod_4, Vars.Concat__132_0, Vars.Concat__133_0, Vars.const__739, '', NumDims.n_nrecevier_mod_4);
Vars.Slice__135_0 = subsref(Vars.n_nrecevier_mod_4, Indices);

% Set graph output arguments from Vars and NumDims:
Slice__135_0 = Vars.Slice__135_0;
Slice__135_0NumDims1322 = NumDims.Slice__135_0;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(n_nrecevier_mod_26, n_nrecevier_mod_4, numDataOutputs, params, varargin)
% Function to validate inputs to Shape_To_SliceFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'n_nrecevier_mod_26', isValidArrayInput);
addRequired(p, 'n_nrecevier_mod_4', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, n_nrecevier_mod_26, n_nrecevier_mod_4, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,2);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [n_nrecevier_mod_26, n_nrecevier_mod_4, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(n_nrecevier_mod_26, n_nrecevier_mod_4, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(n_nrecevier_mod_26, n_nrecevier_mod_4, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {n_nrecevier_mod_26, n_nrecevier_mod_4}));
% Make the input variables into unlabelled dlarrays:
n_nrecevier_mod_26 = makeUnlabeledDlarray(n_nrecevier_mod_26);
n_nrecevier_mod_4 = makeUnlabeledDlarray(n_nrecevier_mod_4);
% Permute inputs if requested:
n_nrecevier_mod_26 = permuteInputVar(n_nrecevier_mod_26, inputDataPerms{1}, 4);
n_nrecevier_mod_4 = permuteInputVar(n_nrecevier_mod_4, inputDataPerms{2}, 4);
end

function [Slice__135_0] = postprocessOutput(Slice__135_0, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(Slice__135_0)
        Slice__135_0 = extractdata(Slice__135_0);
    end
end
% Permute outputs if requested:
Slice__135_0 = permuteOutputVar(Slice__135_0, outputDataPerms{1}, 4);
end


%% dlarray functions implementing ONNX operators:

function [Y, numDimsY] = onnxConcat(ONNXAxis, XCell, numDimsXArray)
% Concatentation that treats all empties the same. Necessary because
% dlarray.cat does not allow, for example, cat(1, 1x1, 1x0) because the
% second dimension sizes do not match.

% Copyright 2021 The MathWorks, Inc.

numDimsY = numDimsXArray(1);
XCell(cellfun(@isempty, XCell)) = [];
if isempty(XCell)
    Y = dlarray([]);
else
    if ONNXAxis<0
        ONNXAxis = ONNXAxis + numDimsY;
    end
    DLTAxis = numDimsY - ONNXAxis;
    Y = cat(DLTAxis, XCell{:});
end
end

function [Y, numDimsY] = onnxGather(X, ONNXIdx, ONNXAxis, numDimsX, numDimsIdx)
% Function implementing the ONNX Gather operator

% In ONNX, 'Gather' first indexes into dimension ONNXAxis of data, using
% the contents of ONNXIdx as the indices. Then, it reshapes the ONNXAxis
% into the shape of ONNXIdx.
%   Example 1:
% Suppose data has shape [2 3 4 5], ONNXIdx has shape [6 7], and axis=1.
% The result has shape [2 6 7 4 5].
%   Example 2:
% Suppose data has shape [2 3 4 5], ONNXIdx has shape [6], and axis=1.
% The result has shape [2 6 4 5].
%   Example 3:
% Suppose data has shape [2 3 4 5], ONNXIdx has shape [] (a scalar), and axis=1.
% The result has shape [2 4 5].
%
% Since we're using reverse indexing relative to ONNX, in this function
% data and ONNXIdx both have reversed dimension ordering.

% Copyright 2020-2021 The MathWorks, Inc.

numDimsY = numDimsIdx + (numDimsX - 1);
if isempty(X)
    Y = X;
    return;
end
% (1) First, do the subsref part of Gather
if ONNXAxis<0
    ONNXAxis = ONNXAxis + numDimsX;                                 % Axis can be negative. Convert it to its positive equivalent.
end
dltAxis = numDimsX - ONNXAxis;                                      % Convert axis to DLT. ONNXAxis is origin 0 and we index from the end
ONNXIdx(ONNXIdx<0) = ONNXIdx(ONNXIdx<0) + size(X, dltAxis);         % ONNXIdx can have negative components. Make them positive.
dltIdx  = extractdata(ONNXIdx) + 1;                                 % ONNXIdx is origin-0 in ONNX, so add 1 to get dltIdx
% Use subsref to index into data
Indices.subs = repmat({':'}, 1, numDimsX);
Indices.subs{dltAxis} = dltIdx(:);                                  % Index as a column to ensure the output is 1-D in the indexed dimension (for now).
Indices.type = '()';
Y = subsref(X, Indices);
% (2) Now do the reshaping part of Gather
shape = size(Y, 1:numDimsX);
if numDimsIdx == 0
    % Delete the indexed dimension
    shape(dltAxis) = [];
elseif numDimsIdx > 1
    % Reshape the indexed dimension into the shape of ONNXIdx
    shape = [shape(1:dltAxis-1) size(ONNXIdx, 1:numDimsIdx) shape(dltAxis+1:end)];
end
% Extend the shape to 2D so it's valid MATLAB
if numel(shape) < 2
    shape = [shape ones(1,2-numel(shape))];
end
Y = reshape(Y, shape);
end

function [Y, numDimsY] = onnxShape(X, numDimsX, startAxis, endAxis)
% Implements the ONNX Shape operator
% Return the reverse ONNX shape as a 1D column vector

% Copyright 2020-2024 The MathWorks, Inc.

switch numDimsX
    case 0
        if isempty(X)
            Y = dlarray(0);
        else
            Y = dlarray(1);
        end
    case 1
        if isempty(X)
            Y = dlarray(0);
        else
            Y = dlarray(size(X,1));
        end
    otherwise
        if(endAxis<0)
            %  If the endAxis is smaller than 0 after converting it positive,
            % the endAxis is 0
            endAxis = max(0, numDimsX + endAxis);
        end
        if(startAxis<0)
            %  If the startAxis is smaller than 0 after converting it positive,
            % the startAxis is 0
            startAxis = max(0, numDimsX + startAxis);
        end
        % transform startAxis and endAxis from 0 index to 1 index
        startAxis = startAxis + 1;
        endAxis = endAxis + 1;
        % if startAxis is larger than numDimsX or endAxis is larger than
        % numDimsX + 1, cramp it to the upper bound. The endAxis is exclusive,
        % transform it to MATLAB inclusive way
        endAxis = min(endAxis, numDimsX + 1) - 1;
        startAxis = min(startAxis, numDimsX);
        if endAxis < startAxis || endAxis == 0
            Y = dlarray(0);
        else
            Y = dlarray(fliplr(size(X, (numDimsX-endAxis+1):(numDimsX-startAxis+1)))');
        end
end
numDimsY = 1;
end

function [Y, numDimsY] = onnxSqueeze(X, ONNXAxes, numDimsX)
% Implements the ONNX Squeeze operator

% Copyright 2020 The MathWorks, Inc.

if numDimsX == 0
    Y = X;
    numDimsY = numDimsX;
else
    % Find the new ONNX shape
    curOShape = size(X, numDimsX:-1:1);
    if isempty(ONNXAxes)
        newOShape = curOShape(curOShape ~= 1);
    else
        ONNXAxes(ONNXAxes<0) = ONNXAxes(ONNXAxes<0) + numDimsX;
        newOShape = curOShape;
        newOShape(ONNXAxes+1) = [];
    end
    % Get numDimsY from ONNX shape
    numDimsY  = numel(newOShape);
    newMShape = [fliplr(newOShape) ones(1, 2-numDimsY)];    % Append 1's to shape if numDims<2
    Y         = reshape(X, newMShape);
end
end

function [S, numDimsY] = prepareSliceArgs(X, Starts, Ends, Axes, Steps, numDimsX)
% Prepares arguments for implementing the ONNX Slice operator

%   Copyright 2020 The MathWorks, Inc.

% Starts, Ends and Axes are all origin 0. Axes refer to the ONNX dimension
% ordering, but X uses the reverse, DLT ordering. Starts, Ends, Axes, and
% Steps correspond positionally. Axes and Steps may be omitted, with
% defaults described in the ONNX spec.

% Set default Axes and Steps if not supplied
if isempty(Axes)
    Axes = 0:numDimsX-1;   % All axes
end
Axes(Axes<0) = Axes(Axes<0) + numDimsX; % Handle negative Axes.
if isempty(Steps)
    Steps = ones(1, numel(Starts));
end
% Init all dims to :
S.subs = repmat({':'}, 1, numDimsX);
S.type = '()';
% Set Starts and Ends for each axis
for i = 1:numel(Axes)
    DLTDim = numDimsX - Axes(i);                                               % The DLT dim is the reverse of the ONNX dim.
    % "If a negative value is passed for any of the start or end indices,
    % it represents number of elements before the end of that dimension."
    if Starts(i) < 0
        Starts(i) = size(X,DLTDim) + Starts(i);
    end
    if Ends(i) < 0
        Ends(i) = max(-1, size(X,DLTDim) + Ends(i));                        % The -1 case is when we're slicing backward and want to include 0.
    end
    % "If the value passed to start or end is larger than the n (the number
    % of elements in this dimension), it represents n."
    if Starts(i) > size(X,DLTDim)
        Starts(i) = size(X,DLTDim);
    end
    if Ends(i) > size(X,DLTDim)
        Ends(i) = size(X,DLTDim);
    end
    if Steps(i) > 0
        S.subs{DLTDim} = 1 + (Starts(i) : Steps(i) : Ends(i)-1);            % 1 + (Origin 0 indexing with end index excluded)
    else
        S.subs{DLTDim} = 1 + (Starts(i) : Steps(i) : Ends(i)+1);            % 1 + (Origin 0 indexing with end index excluded)
    end
end
numDimsY = numDimsX;
end

function [newShape, numDimsY] = prepareUnsqueezeArgs(X, ONNXAxes, numDimsX)
% Prepares arguments for implementing the ONNX Unsqueeze operator

%   Copyright 2020-2021 The MathWorks, Inc.

numDimsY = numDimsX + numel(ONNXAxes);
ONNXAxes = extractdata(ONNXAxes);
ONNXAxes(ONNXAxes<0) = ONNXAxes(ONNXAxes<0) + numDimsY;
ONNXAxes = sort(ONNXAxes);                                              % increasing order
if numDimsY == 1
    newShape = size(X);
else
    DLTAxes  = flip(numDimsY - ONNXAxes);                                  % increasing order
    newShape = ones(1, numDimsY);
    posToSet = setdiff(1:numDimsY, DLTAxes, 'stable');
    newShape(posToSet) = size(X, 1:numel(posToSet));
end
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.

%   Copyright 2020 The MathWorks, Inc.

if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

%   Copyright 2020-2021 The MathWorks, Inc.

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more

    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);

    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end

    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);

    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));

    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;

    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray

%   Copyright 2020-2021 The MathWorks, Inc.

if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)

%   Copyright 2020 The MathWorks, Inc.

% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in
% t.
%   Copyright 2020 The MathWorks, Inc.

for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
