classdef Shape_To_ReshapeLayer1318 < nnet.layer.Layer & nnet.layer.Formattable
    % A custom layer auto-generated while importing an ONNX network.

    %#codegen
    %#ok<*PROPLC>
    %#ok<*NBRAK>
    %#ok<*INUSL>
    %#ok<*VARARG>

    properties (Learnable)
        const_fold_opt__5883
        n_nrecevier_mod_20
        n_nrecevier_mod_24
    end

    properties
        ONNXParams         % An ONNXParameters object containing parameters used by this layer.
    end

    methods
        function this = Shape_To_ReshapeLayer1318(name, onnxParams)
            this.Name = name;
            this.NumInputs = 2;
            this.OutputNames = {'n_nrecevier_mod_26'};
            this.ONNXParams = onnxParams;
            this.const_fold_opt__5883 = onnxParams.Learnables.const_fold_opt__5883;
            this.n_nrecevier_mod_20 = onnxParams.Learnables.n_nrecevier_mod_20;
            this.n_nrecevier_mod_24 = onnxParams.Learnables.n_nrecevier_mod_24;
        end

        function [n_nrecevier_mod_26] = predict(this, input, inputNumDims)
            if isdlarray(input)
                input = stripdims(input);
            end
            inputNumDims = numel(inputNumDims);
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.const_fold_opt__5883 = this.const_fold_opt__5883;
            onnxParams.Learnables.n_nrecevier_mod_20 = this.n_nrecevier_mod_20;
            onnxParams.Learnables.n_nrecevier_mod_24 = this.n_nrecevier_mod_24;
            [n_nrecevier_mod_26, n_nrecevier_mod_26NumDims] = Shape_To_ReshapeFcn(input, inputNumDims, onnxParams, 'Training', false, ...
                'InputDataPermutation', {['as-is'], ['as-is']}, ...
                'OutputDataPermutation', {[2 3 4 1], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {n_nrecevier_mod_26}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'Shape_To_ReshapeLayer1318');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Shape_To_ReshapeLayer1318'));
            end
            n_nrecevier_mod_26 = dlarray(single(n_nrecevier_mod_26), 'SSCB');
            if ~coder.target('MATLAB')
                n_nrecevier_mod_26 = extractdata(n_nrecevier_mod_26);
            end
        end

        function [n_nrecevier_mod_26] = forward(this, input, inputNumDims)
            if isdlarray(input)
                input = stripdims(input);
            end
            inputNumDims = numel(inputNumDims);
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.const_fold_opt__5883 = this.const_fold_opt__5883;
            onnxParams.Learnables.n_nrecevier_mod_20 = this.n_nrecevier_mod_20;
            onnxParams.Learnables.n_nrecevier_mod_24 = this.n_nrecevier_mod_24;
            [n_nrecevier_mod_26, n_nrecevier_mod_26NumDims] = Shape_To_ReshapeFcn(input, inputNumDims, onnxParams, 'Training', true, ...
                'InputDataPermutation', {['as-is'], ['as-is']}, ...
                'OutputDataPermutation', {[2 3 4 1], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {n_nrecevier_mod_26}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'Shape_To_ReshapeLayer1318');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Shape_To_ReshapeLayer1318'));
            end
            n_nrecevier_mod_26 = dlarray(single(n_nrecevier_mod_26), 'SSCB');
            if ~coder.target('MATLAB')
                n_nrecevier_mod_26 = extractdata(n_nrecevier_mod_26);
            end
        end
    end
end

function [n_nrecevier_mod_26, n_nrecevier_mod_26NumDims, state] = Shape_To_ReshapeFcn(input, inputNumDims, params, varargin)
%SHAPE_TO_RESHAPEFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 18
%
% Variable names in this function are taken from the original ONNX file.
%
% [N_NRECEVIER_MOD_26] = Shape_To_ReshapeFcn(INPUT, PARAMS)
%			- Evaluates the imported ONNX network SHAPE_TO_RESHAPEFCN with input(s)
%			INPUT and the imported network parameters in PARAMS. Returns
%			network output(s) in N_NRECEVIER_MOD_26.
%
% [N_NRECEVIER_MOD_26, STATE] = Shape_To_ReshapeFcn(INPUT, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = Shape_To_ReshapeFcn(INPUT, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% INPUT
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  INPUT:		[unk__6051, unk__6052, unk__6053, 8]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% N_NRECEVIER_MOD_26
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  N_NRECEVIER_MOD_26:		[Unknown, Unknown, Unknown, Unknown]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(input, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'input'}, {input}, [inputNumDims]);
% Call the top-level graph function:
[n_nrecevier_mod_26, n_nrecevier_mod_26NumDims, state] = Shape_To_ReshapeGraph1315(input, NumDims.input, Vars, NumDims, Training, params.State);
% Postprocess the output data
[n_nrecevier_mod_26] = postprocessOutput(n_nrecevier_mod_26, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [n_nrecevier_mod_26, n_nrecevier_mod_26NumDims1317, state] = Shape_To_ReshapeGraph1315(input, inputNumDims1316, Vars, NumDims, Training, state)
% Function implementing the graph 'Shape_To_ReshapeGraph1315'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.input = input;
NumDims.input = inputNumDims1316;

% Execute the operators:
% Shape:
[Vars.n_nrecevier_mod_29, NumDims.n_nrecevier_mod_29] = onnxShape(Vars.input, NumDims.input, 0, NumDims.input+1);

% Cast:
if islogical(Vars.n_nrecevier_mod_29)
    Vars.n_nrecevier_mod_29 = single(Vars.n_nrecevier_mod_29);
end
Vars.n_nrecevier_mod_30 = cast(int32(extractdata(Vars.n_nrecevier_mod_29)), 'like', Vars.n_nrecevier_mod_29);
NumDims.n_nrecevier_mod_30 = NumDims.n_nrecevier_mod_29;

% Cast:
if islogical(Vars.n_nrecevier_mod_30)
    Vars.n_nrecevier_mod_30 = single(Vars.n_nrecevier_mod_30);
end
Vars.n_nrecevier_mod_27 = cast(int64(extractdata(Vars.n_nrecevier_mod_30)), 'like', Vars.n_nrecevier_mod_30);
NumDims.n_nrecevier_mod_27 = NumDims.n_nrecevier_mod_30;

% Slice:
[Indices, NumDims.n_nrecevier_mod_48] = prepareSliceArgs(Vars.n_nrecevier_mod_30, Vars.const_starts__1988, Vars.const_starts__1983, Vars.const_axes__4255, '', NumDims.n_nrecevier_mod_30);
Vars.n_nrecevier_mod_48 = subsref(Vars.n_nrecevier_mod_30, Indices);

% Slice:
[Indices, NumDims.n_nrecevier_mod_47] = prepareSliceArgs(Vars.n_nrecevier_mod_30, Vars.const_axes__4255, Vars.const_starts__1988, Vars.const_axes__4255, '', NumDims.n_nrecevier_mod_30);
Vars.n_nrecevier_mod_47 = subsref(Vars.n_nrecevier_mod_30, Indices);

% Slice:
[Indices, NumDims.n_nrecevier_mod_49] = prepareSliceArgs(Vars.n_nrecevier_mod_30, Vars.const_starts__1983, Vars.const__738, Vars.const_axes__4255, '', NumDims.n_nrecevier_mod_30);
Vars.n_nrecevier_mod_49 = subsref(Vars.n_nrecevier_mod_30, Indices);

% Slice:
[Indices, NumDims.n_nrecevier_mod_51] = prepareSliceArgs(Vars.n_nrecevier_mod_30, Vars.const__2055, Vars.const_ends__3053, Vars.const_axes__4255, '', NumDims.n_nrecevier_mod_30);
Vars.n_nrecevier_mod_51 = subsref(Vars.n_nrecevier_mod_30, Indices);

% Squeeze:
[Vars.n_nrecevier_mod_50, NumDims.n_nrecevier_mod_50] = onnxSqueeze(Vars.n_nrecevier_mod_51, Vars.const_axes__4255, NumDims.n_nrecevier_mod_51);

% Div:
Vars.n_nrecevier_mod_39 = fix(Vars.n_nrecevier_mod_50 ./ Vars.n_nrecevier_mod_40);
NumDims.n_nrecevier_mod_39 = max(NumDims.n_nrecevier_mod_50, NumDims.n_nrecevier_mod_40);

% Unsqueeze:
[shape, NumDims.n_nrecevier_mod_46] = prepareUnsqueezeArgs(Vars.n_nrecevier_mod_39, Vars.const_axes__4255, NumDims.n_nrecevier_mod_39);
Vars.n_nrecevier_mod_46 = reshape(Vars.n_nrecevier_mod_39, shape);

% Concat:
[Vars.n_nrecevier_mod_45, NumDims.n_nrecevier_mod_45] = onnxConcat(0, {Vars.n_nrecevier_mod_47, Vars.n_nrecevier_mod_48, Vars.n_nrecevier_mod_49, Vars.const_fold_opt__5912, Vars.n_nrecevier_mod_46}, [NumDims.n_nrecevier_mod_47, NumDims.n_nrecevier_mod_48, NumDims.n_nrecevier_mod_49, NumDims.const_fold_opt__5912, NumDims.n_nrecevier_mod_46]);

% Cast:
if islogical(Vars.n_nrecevier_mod_45)
    Vars.n_nrecevier_mod_45 = single(Vars.n_nrecevier_mod_45);
end
Vars.n_nrecevier_mod_28 = cast(int64(extractdata(Vars.n_nrecevier_mod_45)), 'like', Vars.n_nrecevier_mod_45);
NumDims.n_nrecevier_mod_28 = NumDims.n_nrecevier_mod_45;

% Reshape:
[shape, NumDims.n_nrecevier_mod_19] = prepareReshapeArgs(Vars.input, Vars.n_nrecevier_mod_28, NumDims.input, 0);
Vars.n_nrecevier_mod_19 = reshape(Vars.input, shape{:});

% ReduceMean:
dims = prepareReduceArgs(Vars.const_fold_opt__5883, NumDims.n_nrecevier_mod_19);
Vars.n_nrecevier_mod_43 = mean(Vars.n_nrecevier_mod_19, dims);
NumDims.n_nrecevier_mod_43 = NumDims.n_nrecevier_mod_19;

% Sub:
Vars.n_nrecevier_mod_41 = Vars.n_nrecevier_mod_19 - Vars.n_nrecevier_mod_43;
NumDims.n_nrecevier_mod_41 = max(NumDims.n_nrecevier_mod_19, NumDims.n_nrecevier_mod_43);

% Mul:
Vars.n_nrecevier_mod_42 = Vars.n_nrecevier_mod_41 .* Vars.n_nrecevier_mod_41;
NumDims.n_nrecevier_mod_42 = max(NumDims.n_nrecevier_mod_41, NumDims.n_nrecevier_mod_41);

% ReduceMean:
dims = prepareReduceArgs(Vars.const_fold_opt__5883, NumDims.n_nrecevier_mod_42);
Vars.n_nrecevier_mod_44 = mean(Vars.n_nrecevier_mod_42, dims);
NumDims.n_nrecevier_mod_44 = NumDims.n_nrecevier_mod_42;

% Add:
Vars.n_nrecevier_mod_33 = Vars.n_nrecevier_mod_44 + Vars.n_nrecevier_mod_146;
NumDims.n_nrecevier_mod_33 = max(NumDims.n_nrecevier_mod_44, NumDims.n_nrecevier_mod_146);

% Sqrt:
Vars.n_nrecevier_mod_31 = sqrt(Vars.n_nrecevier_mod_33);
NumDims.n_nrecevier_mod_31 = NumDims.n_nrecevier_mod_33;

% Reciprocal:
Vars.n_nrecevier_mod_32 = 1./(Vars.n_nrecevier_mod_31);
NumDims.n_nrecevier_mod_32 = NumDims.n_nrecevier_mod_31;

% Concat:
[Vars.n_nrecevier_mod_21, NumDims.n_nrecevier_mod_21] = onnxConcat(0, {Vars.const_fold_opt__5935, Vars.const_fold_opt__5935, Vars.const_fold_opt__5935, Vars.const_fold_opt__5912, Vars.n_nrecevier_mod_46}, [NumDims.const_fold_opt__5935, NumDims.const_fold_opt__5935, NumDims.const_fold_opt__5935, NumDims.const_fold_opt__5912, NumDims.n_nrecevier_mod_46]);

% Cast:
if islogical(Vars.n_nrecevier_mod_21)
    Vars.n_nrecevier_mod_21 = single(Vars.n_nrecevier_mod_21);
end
Vars.n_nrecevier_mod_23 = cast(int64(extractdata(Vars.n_nrecevier_mod_21)), 'like', Vars.n_nrecevier_mod_21);
NumDims.n_nrecevier_mod_23 = NumDims.n_nrecevier_mod_21;

% Reshape:
[shape, NumDims.n_nrecevier_mod_25] = prepareReshapeArgs(Vars.n_nrecevier_mod_24, Vars.n_nrecevier_mod_23, NumDims.n_nrecevier_mod_24, 0);
Vars.n_nrecevier_mod_25 = reshape(Vars.n_nrecevier_mod_24, shape{:});

% Reshape:
[shape, NumDims.n_nrecevier_mod_22] = prepareReshapeArgs(Vars.n_nrecevier_mod_20, Vars.n_nrecevier_mod_23, NumDims.n_nrecevier_mod_20, 0);
Vars.n_nrecevier_mod_22 = reshape(Vars.n_nrecevier_mod_20, shape{:});

% Mul:
Vars.n_nrecevier_mod_35 = Vars.n_nrecevier_mod_32 .* Vars.n_nrecevier_mod_22;
NumDims.n_nrecevier_mod_35 = max(NumDims.n_nrecevier_mod_32, NumDims.n_nrecevier_mod_22);

% Mul:
Vars.n_nrecevier_mod_37 = Vars.n_nrecevier_mod_43 .* Vars.n_nrecevier_mod_35;
NumDims.n_nrecevier_mod_37 = max(NumDims.n_nrecevier_mod_43, NumDims.n_nrecevier_mod_35);

% Sub:
Vars.n_nrecevier_mod_38 = Vars.n_nrecevier_mod_25 - Vars.n_nrecevier_mod_37;
NumDims.n_nrecevier_mod_38 = max(NumDims.n_nrecevier_mod_25, NumDims.n_nrecevier_mod_37);

% Mul:
Vars.n_nrecevier_mod_36 = Vars.n_nrecevier_mod_19 .* Vars.n_nrecevier_mod_35;
NumDims.n_nrecevier_mod_36 = max(NumDims.n_nrecevier_mod_19, NumDims.n_nrecevier_mod_35);

% Add:
Vars.n_nrecevier_mod_34 = Vars.n_nrecevier_mod_36 + Vars.n_nrecevier_mod_38;
NumDims.n_nrecevier_mod_34 = max(NumDims.n_nrecevier_mod_36, NumDims.n_nrecevier_mod_38);

% Reshape:
[shape, NumDims.n_nrecevier_mod_26] = prepareReshapeArgs(Vars.n_nrecevier_mod_34, Vars.n_nrecevier_mod_27, NumDims.n_nrecevier_mod_34, 0);
Vars.n_nrecevier_mod_26 = reshape(Vars.n_nrecevier_mod_34, shape{:});

% Set graph output arguments from Vars and NumDims:
n_nrecevier_mod_26 = Vars.n_nrecevier_mod_26;
n_nrecevier_mod_26NumDims1317 = NumDims.n_nrecevier_mod_26;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(input, numDataOutputs, params, varargin)
% Function to validate inputs to Shape_To_ReshapeFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'input', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, input, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(input, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(input, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {input}));
% Make the input variables into unlabelled dlarrays:
input = makeUnlabeledDlarray(input);
% Permute inputs if requested:
input = permuteInputVar(input, inputDataPerms{1}, 4);
end

function [n_nrecevier_mod_26] = postprocessOutput(n_nrecevier_mod_26, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(n_nrecevier_mod_26)
        n_nrecevier_mod_26 = extractdata(n_nrecevier_mod_26);
    end
end
% Permute outputs if requested:
n_nrecevier_mod_26 = permuteOutputVar(n_nrecevier_mod_26, outputDataPerms{1}, 4);
end


%% dlarray functions implementing ONNX operators:

function [Y, numDimsY] = onnxConcat(ONNXAxis, XCell, numDimsXArray)
% Concatentation that treats all empties the same. Necessary because
% dlarray.cat does not allow, for example, cat(1, 1x1, 1x0) because the
% second dimension sizes do not match.

% Copyright 2021 The MathWorks, Inc.

numDimsY = numDimsXArray(1);
XCell(cellfun(@isempty, XCell)) = [];
if isempty(XCell)
    Y = dlarray([]);
else
    if ONNXAxis<0
        ONNXAxis = ONNXAxis + numDimsY;
    end
    DLTAxis = numDimsY - ONNXAxis;
    Y = cat(DLTAxis, XCell{:});
end
end

function [Y, numDimsY] = onnxShape(X, numDimsX, startAxis, endAxis)
% Implements the ONNX Shape operator
% Return the reverse ONNX shape as a 1D column vector

% Copyright 2020-2024 The MathWorks, Inc.

switch numDimsX
    case 0
        if isempty(X)
            Y = dlarray(0);
        else
            Y = dlarray(1);
        end
    case 1
        if isempty(X)
            Y = dlarray(0);
        else
            Y = dlarray(size(X,1));
        end
    otherwise
        if(endAxis<0)
            %  If the endAxis is smaller than 0 after converting it positive,
            % the endAxis is 0
            endAxis = max(0, numDimsX + endAxis);
        end
        if(startAxis<0)
            %  If the startAxis is smaller than 0 after converting it positive,
            % the startAxis is 0
            startAxis = max(0, numDimsX + startAxis);
        end
        % transform startAxis and endAxis from 0 index to 1 index
        startAxis = startAxis + 1;
        endAxis = endAxis + 1;
        % if startAxis is larger than numDimsX or endAxis is larger than
        % numDimsX + 1, cramp it to the upper bound. The endAxis is exclusive,
        % transform it to MATLAB inclusive way
        endAxis = min(endAxis, numDimsX + 1) - 1;
        startAxis = min(startAxis, numDimsX);
        if endAxis < startAxis || endAxis == 0
            Y = dlarray(0);
        else
            Y = dlarray(fliplr(size(X, (numDimsX-endAxis+1):(numDimsX-startAxis+1)))');
        end
end
numDimsY = 1;
end

function [Y, numDimsY] = onnxSqueeze(X, ONNXAxes, numDimsX)
% Implements the ONNX Squeeze operator

% Copyright 2020 The MathWorks, Inc.

if numDimsX == 0
    Y = X;
    numDimsY = numDimsX;
else
    % Find the new ONNX shape
    curOShape = size(X, numDimsX:-1:1);
    if isempty(ONNXAxes)
        newOShape = curOShape(curOShape ~= 1);
    else
        ONNXAxes(ONNXAxes<0) = ONNXAxes(ONNXAxes<0) + numDimsX;
        newOShape = curOShape;
        newOShape(ONNXAxes+1) = [];
    end
    % Get numDimsY from ONNX shape
    numDimsY  = numel(newOShape);
    newMShape = [fliplr(newOShape) ones(1, 2-numDimsY)];    % Append 1's to shape if numDims<2
    Y         = reshape(X, newMShape);
end
end

function dims = prepareReduceArgs(ONNXAxes, numDimsX)
% Prepares arguments for implementing the ONNX Reduce operator

%   Copyright 2020 The MathWorks, Inc.

if isempty(ONNXAxes)
    ONNXAxes = 0:numDimsX-1;   % All axes
end
ONNXAxes(ONNXAxes<0) = ONNXAxes(ONNXAxes<0) + numDimsX;
dims = numDimsX - ONNXAxes;
end

function [DLTShape, numDimsY] = prepareReshapeArgs(X, ONNXShape, numDimsX, allowzero)
% Prepares arguments for implementing the ONNX Reshape operator

%   Copyright 2020-2024 The MathWorks, Inc.

ONNXShape = flip(extractdata(ONNXShape));            % First flip the shape to make it correspond to the dimensions of X.
% In ONNX, 0 means "unchanged" if allowzero is false, and -1 means "infer". In DLT, there is no
% "unchanged", and [] means "infer".
DLTShape = num2cell(ONNXShape);                      % Make a cell array so we can include [].
% Replace zeros with the actual size if allowzero is false
if any(ONNXShape==0) && allowzero==0
    i0 = find(ONNXShape==0);
    DLTShape(i0) = num2cell(size(X, numDimsX - numel(ONNXShape) + i0));  % right-align the shape vector and dims
end
if any(ONNXShape == -1)
    % Replace -1 with []
    i = ONNXShape == -1;
    DLTShape{i} = [];
end
if numel(DLTShape)==1
    DLTShape = [DLTShape 1];
end
numDimsY = numel(ONNXShape);
end

function [S, numDimsY] = prepareSliceArgs(X, Starts, Ends, Axes, Steps, numDimsX)
% Prepares arguments for implementing the ONNX Slice operator

%   Copyright 2020 The MathWorks, Inc.

% Starts, Ends and Axes are all origin 0. Axes refer to the ONNX dimension
% ordering, but X uses the reverse, DLT ordering. Starts, Ends, Axes, and
% Steps correspond positionally. Axes and Steps may be omitted, with
% defaults described in the ONNX spec.

% Set default Axes and Steps if not supplied
if isempty(Axes)
    Axes = 0:numDimsX-1;   % All axes
end
Axes(Axes<0) = Axes(Axes<0) + numDimsX; % Handle negative Axes.
if isempty(Steps)
    Steps = ones(1, numel(Starts));
end
% Init all dims to :
S.subs = repmat({':'}, 1, numDimsX);
S.type = '()';
% Set Starts and Ends for each axis
for i = 1:numel(Axes)
    DLTDim = numDimsX - Axes(i);                                               % The DLT dim is the reverse of the ONNX dim.
    % "If a negative value is passed for any of the start or end indices,
    % it represents number of elements before the end of that dimension."
    if Starts(i) < 0
        Starts(i) = size(X,DLTDim) + Starts(i);
    end
    if Ends(i) < 0
        Ends(i) = max(-1, size(X,DLTDim) + Ends(i));                        % The -1 case is when we're slicing backward and want to include 0.
    end
    % "If the value passed to start or end is larger than the n (the number
    % of elements in this dimension), it represents n."
    if Starts(i) > size(X,DLTDim)
        Starts(i) = size(X,DLTDim);
    end
    if Ends(i) > size(X,DLTDim)
        Ends(i) = size(X,DLTDim);
    end
    if Steps(i) > 0
        S.subs{DLTDim} = 1 + (Starts(i) : Steps(i) : Ends(i)-1);            % 1 + (Origin 0 indexing with end index excluded)
    else
        S.subs{DLTDim} = 1 + (Starts(i) : Steps(i) : Ends(i)+1);            % 1 + (Origin 0 indexing with end index excluded)
    end
end
numDimsY = numDimsX;
end

function [newShape, numDimsY] = prepareUnsqueezeArgs(X, ONNXAxes, numDimsX)
% Prepares arguments for implementing the ONNX Unsqueeze operator

%   Copyright 2020-2021 The MathWorks, Inc.

numDimsY = numDimsX + numel(ONNXAxes);
ONNXAxes = extractdata(ONNXAxes);
ONNXAxes(ONNXAxes<0) = ONNXAxes(ONNXAxes<0) + numDimsY;
ONNXAxes = sort(ONNXAxes);                                              % increasing order
if numDimsY == 1
    newShape = size(X);
else
    DLTAxes  = flip(numDimsY - ONNXAxes);                                  % increasing order
    newShape = ones(1, numDimsY);
    posToSet = setdiff(1:numDimsY, DLTAxes, 'stable');
    newShape(posToSet) = size(X, 1:numel(posToSet));
end
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.

%   Copyright 2020 The MathWorks, Inc.

if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

%   Copyright 2020-2021 The MathWorks, Inc.

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more

    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);

    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end

    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);

    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));

    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;

    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray

%   Copyright 2020-2021 The MathWorks, Inc.

if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)

%   Copyright 2020 The MathWorks, Inc.

% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in
% t.
%   Copyright 2020 The MathWorks, Inc.

for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
